import React from "react";

function MathematicsContent_1() {
  return (
    <div className="App">
      <section className="services-section ptb-100 gray-light-bg">
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-md-10">
              <div className="section-heading text-center mb-5">
                {/* <strong className="color-secondary">Our Services</strong> */}
                <h2>Report on Numeracy</h2>
                <hr></hr>
              </div>
            </div>
          </div>
          <div>
            <h2>
              <span>TASK 1</span>
            </h2>
            <h4>
              <span>Reflective log</span>
            </h4>
            <p>
              <span>
                From the above self analysis it can be analysed that I know
                numeracy regarding to the interest rate and interest mount
                calculation. I aware with mainly two types of interest
                calculation methods which are such as simple interest as well as
                compound interest rate. There are different formulas for both
                the calculation and helps to determine that how much some of
                money will be generated by the investor after making investment
                for particular period of time. I can easily derive time,
                principle amount as well as interest rate for annual,
                semi-annual and quarterly basis. Hence, it can be said that I
                have good command on the simple and compound interest rate
                calculation.
              </span>
            </p>
            <p>
              <span>
                Moreover, it can be said that I am able to analyse future value
                of any kind of investment with the help of net present value.
                From this I clearly understand that when future value of
                potential investment will be positive then should put money in
                that. On the other hand side, when value of NPV comes negative
                then there is no chance to make investment in that. Further,
                criteria about which I am not that much aware and needs more
                practice which is such as linear equation. I can make the
                scatter graph but unable to derive linear equation which lead to
                influence proper decisions as well as analysis. According to the
                frequency distribution I am able to make the table of frequency
                distribution easily and in an appropriate manner. There is a
                problem related to respective thing that for make the histogram
                and interpret it I need more practice.
              </span>
            </p>
            <p>
              <span>
                On the other side in terms of probability distribution I am not
                aware about it as well as unable to calculate probability of any
                occurrence which may happen in the future. I can understand
                about probability after analysing and researching on that but
                not able to compute any kind of calculated if calculator
                provided then as well. In regarding to this, I cannot do
                calculation of exchange rate if they give training they it may
                be possible but not sure.
              </span>
            </p>
            <h4>
              <span>Two examples of real life</span>
            </h4>
            <p>
              <span>
                I have applied my ability of interest rate calculation in the
                real life when I made an investment in an avenue. The person at
                where I make investment, he provides me less money in comparison
                to real interest amount. Further, I show to him proper
                calculation about that and take all the calculated and proper
                money along with principle amount.
              </span>
            </p>
            <p>
              <span>
                Another example relies with the future value calculation using
                net present value tool. When my father going to purchase a new
                equipment in their business then they have two mutually
                exclusive equipments. Further, by using NPV method I derive
                future value of both the equipments and by comparing he choose
                one equipment which has higher future value of its initial cost.
              </span>
            </p>
            <h3>
              <span>SECTION 1</span>
            </h3>
            <h4>
              <span>QUESTION 1</span>
            </h4>
            <p>
              <span>
                <strong>A. One power law</strong>
              </span>
            </p>
            <p>
              <span>
                In the numeracy criteria, there are different kinds of laws and
                regulations are to be use by the analyser. Among them one power
                law is describes that a particular number having multiplications
                up to which how many levels. There are mainly three types of
                powers on any number such as zero, negative as well as positive.
                In the one power only one digit is there for a number.
              </span>
            </p>
            <p>
              <span>
                <strong>B. One root law</strong>
              </span>
            </p>
            <p>
              <span>
                Apart from the above mentioned law of one power there are
                another law used in the numeracy is such as law of one root
                which is identified as square root as well. The value of square
                root is fractional value or index in the actual manner. Further
                it denotes by symbol which is such as“<strong>√</strong>”.
              </span>
            </p>
            <p>
              <span>
                <strong>C. Simplification of one power law</strong>
              </span>
            </p>
            <p>
              <span>
                The power law simplify by three ways which are such as zero,
                positive and negative which is along with example described
                below:
              </span>
            </p>
            <p>
              <span>
                Zero = 6^0 = 1. Value of digit comes always one when there is
                zero power.
              </span>
            </p>
            <p>
              <span>
                Positive = 6^2 = 36. Value of positive power is multiplications
                of same digit.
              </span>
            </p>
            <p>
              <span>
                Negative = 6^-2 = 0.028. When there is negative power then value
                of digit reduce from original.
              </span>
            </p>
            <p>
              <span>
                <strong>D. Simplification of one root law</strong>
              </span>
            </p>
            <p>
              <span>
                Law of one root is to be simplified with the help of below given
                example:
              </span>
            </p>
            <p>
              <span>
                <strong>√</strong>16 = 4. Value of income digit is power of the
                outcome digit where power remains same of the respective digit.
              </span>
            </p>
            <h3>
              <span>QUESTION 2</span>
            </h3>
            <h4>
              <span>A. Simple interest amount</span>
            </h4>
            <div class="content-table">
              <table>
                <tbody>
                  <tr>
                    <td>
                      <p>
                        <span>Principle amount</span>
                      </p>
                    </td>
                    &emsp;&emsp;
                    <td>
                      <p>
                        <span>£17500</span>
                      </p>
                    </td>
                  </tr>
                  <tr>
                    <td>
                      <p>
                        <span>Interest rate per annum</span>
                      </p>
                    </td>
                    &emsp;&emsp;
                    <td>
                      <p>
                        <span>8%</span>
                      </p>
                    </td>
                  </tr>
                  <tr>
                    <td>
                      <p>
                        <span>Time</span>
                      </p>
                    </td>
                    &emsp;&emsp;
                    <td>
                      <p>
                        <span>3 years</span>
                      </p>
                    </td>
                  </tr>
                  <tr>
                    <td>
                      <p>
                        <span>Simple interest</span>
                      </p>
                    </td>
                    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
                    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
                    &emsp;&emsp;
                    <td>
                      <p>
                        <span>P*R*T / 100</span>
                      </p>
                      <p>
                        <span>= 17500 * 8 * 3 / 100</span>
                      </p>
                      <p>
                        <span>= £4200</span>
                      </p>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
            <p>
              <span>
                In the present case when A invest amount worth of £17500 for 3
                year on the rate of 8% then return in terms of simple interest
                will be worth of £4200. Further, total amount after three years
                will become £17500+£4200 = £21700.
              </span>
            </p>
            <h4>
              <span>B. Compound interest yearly</span>
            </h4>
            <p>
              <span>C = P [(1+r)n – 1]</span>
            </p>
            <p>
              <span>= 17500 [(1+0.08)3 – 1]</span>
            </p>
            <p>
              <span>= 17500 * 0.2597</span>
            </p>
            <p>
              <span>= £4544.75</span>
            </p>
            <p>
              <span>
                Total amount after 3 years will be worth of £17500 + £4544.75 =
                £22044.75.
              </span>
            </p>
            <h4>
              <span>C. Compound interest semi-annually</span>
            </h4>
            <p>
              <span>C = P [(1+r/2) 2*n – 1]</span>
            </p>
            <p>
              <span>= 17500 [(1+0.08 / 2) 2*3 – 1]</span>
            </p>
            <p>
              <span>= 17500 * 0.2653</span>
            </p>
            <p>
              <span>= £4642.75</span>
            </p>
            <p>
              <span>
                Total amount after 3 years will be worth of £17500 + £4642.75 =
                £22142.75.
              </span>
            </p>
            <h4>
              <span>D. Compound interest quarterly</span>
            </h4>
            <p>
              <span>C = P [(1+r/4) 4*n – 1]</span>
            </p>
            <p>
              <span>= 17500 [(1+0.08 / 4) 4*3 – 1]</span>
            </p>
            <p>
              <span>= 17500 * 0.2682</span>
            </p>
            <p>
              <span>= £4693.5</span>
            </p>
            <p>
              <span>
                Total amount after 3 years will be worth of £17500 + £4693.5 =
                £22193.5.
              </span>
            </p>
            <h3>
              <span>QUESTION 3</span>
            </h3>
            <h4>
              <span>A. Amount which she should invest</span>
            </h4>
            <div class="content-table">
              <table>
                <tbody>
                  <tr>
                    <td>
                      <p>
                        <span>Total value</span>
                      </p>
                    </td>
                    &emsp;&emsp;&emsp;
                    <td>
                      <p>
                        <span>£250000</span>
                      </p>
                    </td>
                  </tr>
                  <tr>
                    <td>
                      <p>
                        <span>Time</span>
                      </p>
                    </td>
                    &emsp;&emsp;&emsp;
                    <td>
                      <p>
                        <span>10 years</span>
                      </p>
                    </td>
                  </tr>
                  <tr>
                    <td>
                      <p>
                        <span>Rate of interest</span>
                      </p>
                    </td>
                    &emsp;&emsp;&emsp;
                    <td>
                      <p>
                        <span>3% p.a.</span>
                      </p>
                    </td>
                  </tr>
                  <tr>
                    <td>
                      <p>
                        <span>Principle amount needs to invest</span>
                      </p>
                    </td>
                    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
                    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
                    <td>
                      <p>
                        <span>C = P [(1+r)n]</span>
                      </p>
                      <p>
                        <span>250000 = P (1+0.03)10</span>
                      </p>
                      <p>
                        <span>= £186025.75</span>
                      </p>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
            <h4>
              <span>B. Computation of interest rate</span>
            </h4>
            <div class="content-table">
              <table>
                <tbody>
                  <tr>
                    <td>
                      <p>
                        <span>Principle</span>
                      </p>
                    </td>
                    &emsp;&emsp;&emsp;
                    <td>
                      <p>
                        <span>£4500</span>
                      </p>
                    </td>
                  </tr>
                  <tr>
                    <td>
                      <p>
                        <span>Time</span>
                      </p>
                    </td>
                    &emsp;&emsp;&emsp;
                    <td>
                      <p>
                        <span>10 years</span>
                      </p>
                    </td>
                  </tr>
                  <tr>
                    <td>
                      <p>
                        <span>Balance</span>
                      </p>
                    </td>
                    &emsp;&emsp;&emsp;
                    <td>
                      <p>
                        <span>£7686.65</span>
                      </p>
                    </td>
                  </tr>
                  <tr>
                    <td>
                      <p>
                        <span>Interest rate</span>
                      </p>
                    </td>
                    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
                    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
                    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
                    <td>
                      <p>
                        <span>C = P [(1+r)n]</span>
                      </p>
                      <p>
                        <span>7686.65 = 4500 (1+r)10</span>
                      </p>
                      <p>
                        <span>= 5.5%</span>
                      </p>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          <div>
            <p>
              <span>
                In 2015, recoverable amount is higher than carrying figure so
                there is no journal entry has been made.
              </span>
            </p>
            <h4>
              <span>C. Explaining the reasons for impairment</span>
            </h4>
            <p>
              <span>
                In 2014, carrying amount is $200000, whereas recoverable amount
                implies for $110000. Hence, carrying amount is higher than
                recoverable cost which shows the loss of $90000.&nbsp;Carrying
                cost – recoverable amount&nbsp;$200000 – $110000 = $90000
              </span>
            </p>
            <h4>
              <span>
                D. Presenting the amount of plant and equipment in balance sheet
              </span>
            </h4>
            <p>
              <span>
                In balance sheet, revaluate amount of plant and equipment is
                recorded by business entity after doing final reversal.
              </span>
            </p>
            <h3>
              <span>QUESTION 3</span>
            </h3>
            <h4>
              <span>
                Interpreting the technical requirements and importance of
                international accounting standards
              </span>
            </h4>
            <p>
              <span>
                International&nbsp;<a>Accounting</a>&nbsp;standards have high
                level of importance which ensures high level transparency and
                standardization in the financial statements. Hence, final
                accounts which are prepared according to IFRS are highly
                reliable in nature and thereby helps stakeholders in making
                decisions (Florou, Kosi and Pope, 2017). However, technical
                knowledge is highly required among the individuals or accounting
                personnel to deal with the aspects of International Accounting
                Standards such as IAS 12 and 26 etc. In this, accounting
                personnel must have ability to recognize deferred tax assets and
                liabilities. Moreover, assets, revenue received in advance,
                other liabilities, unrecognized items; consolidated financial
                statements are the main bases of taxation (Warren, 2016). By
                taking into consideration all such bases accounting personnel
                can assess or determine the tax liability. In addition to this,
                in IAS 12 contains rules regarding the measurement of deferred
                tax. Along with this, tax rate are also varied from one year to
                another. In this, accounting personnel is required to update
                with changing rules and policies. Through this, finance manager
                and accounting personnel would become able to determine suitable
                tax liability.&nbsp;In addition to this, IAS 26 serves
                information about retirement plans which can be distinguished
                into two types such as defined benefit and contribution plan.
                Hence, it clearly presents information about the recording,
                measurement and disclosure of information regarding the
                retirement benefit plans. Hence, for effective presentation
                accounting personnel must have knowledge regarding the rules and
                regulations which are related to it (Bond, Govendir and Wells,
                2016). Thus, by considering all such aspects it can be said that
                technical and conceptual knowledge is highly required for
                dealing with the standards more effectively and efficiently.
                Moreover, reporting and measurement aspect of pension plan is
                highly differing from one standard to another (McPhail,
                Macdonald and Ferguson, 2016). For instance: UK GAAP has
                different rules in relation to treatment on pension benefits in
                against to IAS. Hence, conceptual understanding and knowledge is
                highly required for dealing with the amount of retirement
                benefits and deferred tax amount.&nbsp;There are several key
                issues which are associated with financial reporting enumerated
                below:
              </span>
            </p>
            <ul>
              <li>
                <span>
                  Reporting needs and requirements are mentioned in the
                  regulations which business entity requires following for
                  ensuring transparency in the final accounts. However,
                  sometimes is not possible for the business organization to
                  comply with all the rules to the large extent.
                </span>
              </li>
              <li>
                <span>
                  Further, some government authorities have framed and
                  introduced legislation which entail that companies are not
                  obliged to prepare financial statements according to
                  accounting standards. Moreover, sometimes treasurer directives
                  also enforce accounting standard which company has to follow
                  for the preparation of financial statements.
                </span>
              </li>
            </ul>
            <h4>
              <span>References</span>
            </h4>
            <ul style={{ marginLeft: 20, listStyleType: "circle" }}>
              <li>
                <span>
                  Bond, D., Govendir, B. and Wells, P., 2016. An evaluation of
                  asset impairments by Australian firms and whether they were
                  impacted by AASB 136.Accounting &amp; Finance.
                </span>
              </li>
              <li>
                <span>
                  Florou, A., Kosi, U. and Pope, P.F., 2017. Are international
                  accounting standards more credit relevant than domestic
                  standards?.Accounting and Business Research.47(1). pp.1-29.
                </span>
              </li>
              <li>
                <span>
                  McPhail, K., Macdonald, K. and Ferguson, J., 2016. Should the
                  international accounting standards board have responsibility
                  for human rights?.Accounting, Auditing &amp; Accountability
                  Journal.29(4). pp.594-616.
                </span>
              </li>
              <li>
                <span>
                  Warren, C. M., 2016. The impact of International Accounting
                  Standards Board (IASB)/International Financial Reporting
                  Standard 16 (IFRS 16).Property Management.34(3).
                </span>
              </li>
            </ul>
          </div>

          {/* style={{marginLeft:20,listStyleType:'circle'}} */}
        </div>
      </section>
    </div>
  );
}

export default MathematicsContent_1;
